# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Bucketlist.destroy_all
User.destroy_all
Destination.destroy_all
Review.destroy_all
ThingsToDo.destroy_all
AddJoiner.destroy_all

bali = Destination.create(name: "Bali", bio: "Beaches, fresh fruits and amazing things", photo: "https://specials-images.forbesimg.com/imageserve/675172642/960x0.jpg?fit=scale", trip_type: "touristy")
marrakech = Destination.create(name: "Marrakech", bio: "cool place", photo: "https://specials-images.forbesimg.com/imageserve/499553781/960x0.jpg?fit=scale", trip_type: "Adventurous")
london = Destination.create(name: "London", bio: "cool", photo: "https://cdn.londonandpartners.com/assets/73295-640x360-london-skyline-ns.jpg", trip_type: "city")
dhaka = Destination.create(name:  "Dhaka", bio: "populated city", photo: "https://touristplacesbd.com/wp-content/uploads/2019/06/dhaka-city.jpg", trip_type: "citylife")
paris = Destination.create(name: "Paris", bio: "cool", photo: "https://blinkvisa.com/blog/wp-content/uploads/2019/09/eiffel-tower-min.jpg", trip_type: "family")
kualalumpur = Destination.create(name: "Kuala Lumpur", bio: "cool", photo: "https://static.independent.co.uk/s3fs-public/thumbnails/image/2018/08/21/15/kuala-lumpur.jpg?w968h681", trip_type: "city")
bangkok = Destination.create(name: "Bangkok", bio: "cool", photo: "https://253qv1sx4ey389p9wtpp9sj0-wpengine.netdna-ssl.com/wp-content/uploads/2019/01/Bangkok_Thailand_HERO_GettyImages_HERO_1920x1280.jpg", trip_type: "city")
phuket = Destination.create(name: "Phuket", bio: "cool", photo: "https://thumbnails.expedia.com/kyoLsLeBIwMky9IxKYtzwXf_Yt8=/800x533/a.cdn-hotels.com/gdcs/production109/d1280/8a00a6e3-e4e9-46ba-9a82-36154eaf29ea.jpg", trip_type: "relax")


# things to do in PARIS
eiffelTower = ThingsToDo.create(name: "Eiffel Tower", bio: "The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel, whose company designed and built the tower. Constructed from 1887 to 1889 as the entrance to the 1889 World's Fair, it was initially criticised by some of France's leading artists and intellectuals for its design, but it has become a global cultural icon of France and one of the most recognisable structures in the world.", photo: "https://t2.gstatic.com/images?q=tbn:ANd9GcTZqojMuPgBs1hI7sB6dutyGt9oeMf7tX3uDrl58vn_VdTN4wpfIOpCeugZP77x0Ra-mehw3smmmCf0ag", destination: paris)
louvreMuseum = ThingsToDo.create(name: "Louvre Museum", bio: "The Louvre, or the Louvre Museum, is the world's largest art museum and a historic monument in Paris, France. A central landmark of the city, it is located on the Right Bank of the Seine in the city's 1st arrondissement.", photo: "https://dynaimage.cdn.cnn.com/cnn/c_fill,g_auto,w_1200,h_675,ar_16:9/https%3A%2F%2Fcdn.cnn.com%2Fcnnnext%2Fdam%2Fassets%2F190402115305-louvre-museum-paris-pyramid.jpg", destination: paris)
notreDameDeParis = ThingsToDo.create(name: "Notre Dame De Paris", bio: "Notre-Dame de Paris, referred to simply as Notre-Dame, is a medieval Catholic cathedral on the Île de la Cité in the 4th arrondissement of Paris. The cathedral was consecrated to the Virgin Mary and considered to be one of the finest examples of French Gothic architecture.", photo: "https://www.planetware.com/photos-large/F/france-paris-notre-dame-cathedral.jpg", destination: paris)
arcDeTriomphe = ThingsToDo.create(name: "Arc De Triomphe", bio: "The Arc de Triomphe de l'Étoile is one of the most famous monuments in Paris, France, standing at the western end of the Champs-Élysées at the centre of Place Charles de Gaulle, formerly named Place de l'Étoile—the étoile or 'star' of the juncture formed by its twelve radiating avenues.", photo: "https://cdn.pariscityvision.com/library/image/4589.jpg", destination: paris)

# things to do in MARRAKECH
jamaElFnaMarket = ThingsToDo.create(name: "Jama El Fna Market", bio: "Jemaa el-Fnaa is a square and market place in Marrakesh's medina quarter. It remains the main square of Marrakesh, used by locals and tourists.", photo: "https://t1.gstatic.com/images?q=tbn:ANd9GcSYayirsHrFXWvebTqT8ZcS7MMztR6qLcwr2gmKYMq-KAQewL49DIH6xmdSlwwTbCkEdnC3nrqumnH5-A", destination: marrakech)
jardinMajorelle = ThingsToDo.create(name: "Jardin Majorelle", bio: "The Majorelle Garden is a two and half acre botanical garden and artist's landscape garden in Marrakech, Morocco. It was created by the French Orientalist artist, Jacques Majorelle over almost forty years, starting in 1923, and features a Cubist villa designed by the French architect, Paul Sinoir in the 1930s.", photo: "https://assets.atlasobscura.com/media/W1siZiIsInVwbG9hZHMvcGxhY2VfaW1hZ2VzLzUwZWEwNTY5LWZlNjAtNDU4Ny05Y2JkLWVmNjFjOTE2NjYxOTZlMzMxZjg1YjAyZjFjNjk4NV9KYXJkaW4tTWFqb3JlbGxlLTQuSlBHIl0sWyJwIiwidGh1bWIiLCJ4MzkwPiJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA4MSAtYXV0by1vcmllbnQiXV0/Jardin-Majorelle-4.JPG", destination: marrakech)
koutoubia = ThingsToDo.create(name: "Koutoubia", bio: "The Kutubiyya Mosque or Koutoubia Mosque is the largest mosque in Marrakesh, Morocco. The mosque's name is also variably rendered as Jami' al-Kutubiyah, Kutubiya Mosque, Kutubiyyin Mosque, and Mosque of the Booksellers.", photo: "https://lp-cms-production.imgix.net/2019-06/dc6c6aa1c80bd52f90decf31c6fb8f97-koutoubia-mosque.jpg", destination: marrakech)
saadiensTombs = ThingsToDo.create(name: "Saadiens Tombs", bio: "The Saadian Tombs are a historic royal necropolis in Marrakech, Morocco. They date to the time of the Saadian dynasty, and in particular to the reign of Ahmad al-Mansur.", photo: "https://lp-cms-production.imgix.net/2019-06/7d33a05f23f325873b7205a9264fd490-saadian-tombs.jpg", destination: marrakech)

# things to do in BALI
ubud = ThingsToDo.create(name: "Ubud", bio: "The town of Ubud, in the uplands of Bali, Indonesia, is known as a center for traditional crafts and dance. The surrounding Ubud District’s rainforest and terraced rice paddies, dotted with Hindu temples and shrines, are among Bali’s most famous landscapes.", photo: "https://lh3.googleusercontent.com/proxy/I5ej4oHOV5HvyoI5X9YMvBYI_SJbDkRhzSO34b7Rfp8Fuv9-tGbjP9BBzB3dPIfPgrsX2F6CecR5JUoPbM3XqRXxqJCBYS7Ir_riQKuZ2dnYEiMXdNvKH0y67v9TtAspMdRP5yyM0-xerdcicKCma5enjb4qO2I=w357-h238-k-no", destination: bali)
denpasar = ThingsToDo.create(name: "Denpasar", bio: "Denpasar is the capital city and main hub of the Indonesian province of Bali, in the southern part of the island. Laid-back Sanur Beach on the east coast offers sunrise views. The nearby Pura Blanjong Temple contains a stone pillar with a 10th-century inscription.", photo: "https://img.traveltriangle.com/blog/wp-content/uploads/2018/11/cover-for-Denpasar-Temples.jpg", destination: bali)
sacredMonkeyForestSanctuary = ThingsToDo.create(name: "Sacred Monkey Forest Sanctuary", bio: "Mandala Suci Wenara Wana, or well known as Ubud Monkey Forest, is the sanctuary and natural habitat of the Balinese long-tailed Monkey, scientific name Macaca fascicularis.", photo: "https://lh5.googleusercontent.com/proxy/RvhBCiTdRYTB1c5KMIaPHk6A5bXZgfADjlxBQHFDGpOuQ-PMZox-xEzr5Eri7bTG1xFi4d8ekFNE1URJ1Az9QinUlKae0U037uth8zY3Qta7SNmd-IUGXn1ccDBLlsyd6W3ZANMcA6yXdqNK54VXdQKFTxRPwPvG6m6cTbgvtEAF=w296-h202-n-k-no", destination: bali)
candiDasa = ThingsToDo.create(name: "Candi Dasa", bio: "Candi Dasa is a seaside town in eastern Bali that rests on the edge of a fresh water lagoon, named Candi Dasa Lagoon.", photo: "https://lh5.googleusercontent.com/p/AF1QipNddH9WY_jpZmDAEJD3qBIotEteTzh02BISaYpc=w423-h238-k-no", destination: bali)

# things to do in LONDON
bigBen = ThingsToDo.create(name: "Big Ben", bio: "Big Ben is the nickname for the Great Bell of the striking clock at the north end of the Palace of Westminster in London and is usually extended to refer to both the clock and the clock tower.", photo: "https://t2.gstatic.com/images?q=tbn:ANd9GcRQVH03aGv6bmZ_mmyJWxLsJg4rIXWuOsEMZAefeeQV_du1Lgn87IAPW14QTMEhnzpITSnrNS9Z5D0QiA", destination: london)
towerBridge = ThingsToDo.create(name: "Tower Bridge", bio: "Tower Bridge is a combined bascule and suspension bridge in London, built between 1886 and 1894. The bridge crosses the River Thames close to the Tower of London and has become an iconic symbol of London.", photo: "https://t0.gstatic.com/images?q=tbn:ANd9GcTiNMqItapJaxKN2oS5AJ8IlE2esibepJdJ_oaKTvAOLKncczFVdYTNkubJSh1-5Rf5cnfyRVgOOrTCxA", destination: london)
buckinghamPalace = ThingsToDo.create(name: "Buckingham Palace", bio: "Buckingham Palace is the London residence and administrative headquarters of the monarchy of the United Kingdom. Located in the City of Westminster, the palace is often at the centre of state occasions and royal hospitality.", photo: "https://cdn.londonandpartners.com/visit/london-organisations/buckingham-palace/100222-640x360-buckingham-palace-at-dusk-640.jpg", destination: london)
towerOfLondon = ThingsToDo.create(name: "Tower Of London", bio: "The Tower of London, officially Her Majesty's Royal Palace and Fortress of the Tower of London, is a historic castle located on the north bank of the River Thames in central London.", photo: "https://employeebenefits.co.uk/content/uploads/2019/01/Tower-of-London.jpg", destination: london)

# things to do in DHAKA
lalbaghFort = ThingsToDo.create(name: "Lalbagh Fort", bio: "Lalbagh Fort is an incomplete 17th century Mughal fort complex that stands before the Buriganga River in the southwestern part of Dhaka, Bangladesh. The construction was started in 1678 AD by Mughal Subahdar Muhammad Azam Shah who was son of Emperor Aurangzeb and later emperor himself.", photo: "https://i.ytimg.com/vi/cb48AlkfNXU/maxresdefault.jpg", destination: dhaka)
ahsanManzilMuseum = ThingsToDo.create(name: "Ahsan Manzil Museum", bio: "Ahsan Manzil was the official residential palace and seat of the Nawab of Dhaka. The building is situated at Kumartoli along the banks of the Buriganga River in Dhaka, Bangladesh. Construction was started in 1859 and was completed in 1872.", photo: "https://t1.gstatic.com/images?q=tbn:ANd9GcQ9RtFQ4J4vT8ARIzk79QKY3UCwNgLIrRfT6Xu0hkCSERmUQHmuZZvccRpiRtosCCR0_xkKNEOCQyoOGg", destination: dhaka)
sonargaon = ThingsToDo.create(name: "Sonargaon", bio: "Sonargaon is a historic city in central Bangladesh. It is one of the old capitals of the historic region of Bengal and was an administrative center of eastern Bengal. It was also a port and trading center.", photo: "https://t2.gstatic.com/images?q=tbn:ANd9GcTt_SmzADW5Xc55TlMNf78zEDxUC9VuwsI1GSFWRPFjdZn409oW7vw_cvU7zLBfZnYQJX5qIVECdF6yiA", destination: dhaka)
jatiyaSangsadBhaban = ThingsToDo.create(name: "Jatiya Sangsad Bhaban", bio: "Jatiya Sangsad Bhaban or National Parliament House, is the house of the Parliament of Bangladesh, located at Sher-e-Bangla Nagar in the Bangladeshi capital of Dhaka. Designed while the country was still part of a Pakistan by architect Louis Kahn, the complex is one of the largest legislative complexes in the world, comprising 200 acres.", photo: "https://t1.gstatic.com/images?q=tbn:ANd9GcRNFf7M1W_6qkfY8q4CDm_nBDhexVlj0ZxbizEfHun4oApQXhobh-dP0GDEmvheShngrtB8teozLF72SA", destination: dhaka)

# things to do KUALALUMPUR
batuCaves = ThingsToDo.create(name: "Batu Caves", bio: "Batu Caves is a limestone hill that has a series of caves and cave temples in Gombak, Selangor, Malaysia. It takes its name from the Sungai Batu, which flows past the hill. It is the tenth limestone hill from Ampang", photo: "https://lh4.googleusercontent.com/proxy/hCbdGGJgWo_da4u9W7H2uFOK-88MVqWyQyvvds7VGIxsnHk1ti7UIaeLX94T-96v1owBKNZ1w8SONTpLMvhqyoMwFOmaH_tCLqYTs41202tCB7RQ-yaBwpqVde397E2jE3xRiNL6ZuXVySr4RMWUhB218ROUCDKvKbhMULT7_6LR=w296-h202-n-k-no", destination: kualalumpur)
nationalMosqueOfMalaysia = ThingsToDo.create(name: "National Mosque of Malaysia", bio: "The National Mosque of Malaysia is a mosque in Kuala Lumpur, Malaysia. It has a capacity for 15,000 people and is situated among 13 acres of gardens. The original structure was designed by a three-person team from the Public Works Department: UK architect Howard Ashley, and Malaysians Hisham Albakri and Baharuddin Kassim.", photo: "https://lh5.googleusercontent.com/proxy/vxY_MVPjpKq5_JeWnK0f9a8cWpHw3TEVGNYUcDnnGGxHsj4ATsMknemZxf_45KtDlpIOidEh0SzsVyNcju4y8QZDeXF7VqtPjHWnnRSZGBElFdk-YIkQ8Ah58rJSkPhZsUVUR95IjBzaUekDRaf9VkDvXiNtJx6bB8j70jzH4VKj=w296-h202-n-k-no", destination: kualalumpur)
bukitBintang = ThingsToDo.create(name: "Bukit Bintang", bio: "Bukit Bintang is the shopping and entertainment district of Kuala Lumpur, Malaysia. It encompasses Jalan Bukit Bintang and its immediate surrounding areas.", photo: "https://lh4.googleusercontent.com/proxy/S9iv1TEMsEaecv4Cix6GZ7WCuhJg98XmLriTtCvcSRNvk-BYSdnyLncrwU1YgqZlv-vauuwPqUcyUo62QiA446HajXfs_kOqhzEmaixw3L4kRW8kbQCywUdviRkKwg2QlvUldvNvseAW1-gUPaPcM5M2LwwF9wq29X6FgIOSdNbG=w296-h202-n-k-no", destination: kualalumpur)
petronasTwinTowers = ThingsToDo.create(name: "Petronas Twin Towers", bio: "The Petronas Towers, also known as the Petronas Twin Towers, are twin skyscrapers in Kuala Lumpur, Malaysia. According to the Council on Tall Buildings and Urban Habitat's official definition and ranking, they were the tallest buildings in the world from 1998 to 2004.", photo: "https://lh4.googleusercontent.com/proxy/SlWp6MT7cgRx8XKJeB6ie1nlrsy8T88d_qB0KWpYz-hYLtbC5MUAiAWFgUvc65OYkRqisyYVKZrNf80fsAPknk86QNzIqyfABZTrB85T7bG7h7FirNcThJ-Yc2UQcqsqA1HqDYNHLcsmpt_Shfy8vTUptTlpTO4Yb7Prs72bR50o=w296-h202-n-k-no", destination: kualalumpur)

# things to do BANGKOK
theGrandPalace = ThingsToDo.create(name: "The Grand Palace", bio: "The Grand Palace is a complex of buildings at the heart of Bangkok, Thailand. The palace has been the official residence of the Kings of Siam since 1782.", photo: "https://t3.gstatic.com/images?q=tbn:ANd9GcQJDFqGp5SPyJhHpoL5uxpmw2n9C3sZP7QPFz7VY57qLdnhXGbvhmidnyadF4EjO-3jsDgzi02dJar1Iw", destination: bangkok)
watArunRatchavararam = ThingsToDo.create(name: "Wat Arun Ratchavararam", bio: "Wat Arun Ratchawararam Ratchawaramahawihan or Wat Arun is a Buddhist temple in Bangkok Yai district of Bangkok, Thailand, on the Thonburi west bank of the Chao Phraya River.", photo: "https://lh5.googleusercontent.com/proxy/Gr_FCG1alMdHBJH5JXqLJZuuQTVWdF9Q6BBlF49RSF55u1ekHlIO9cAJBKJs9avBF-Ioqt30VWhN9PYICRs9hUCBcWXvW9oA6yLtoDKo44ceZAKVrSf8_QbzXoR3NjzzE3n881AW0tvkz7KSskkwe1756l99zWSngg4ZqIfLcwvu=w296-h202-n-k-no", destination: bangkok)
chatuchakWeekendMarket = ThingsToDo.create(name: "Chatuchak Weekend Market", bio: "The Chatuchak Weekend Market, on Kamphaeng Phet 2 Road, Chatuchak, Bangkok, is the largest market in Thailand. Also known as JJ Market, it has more than 15,000 stalls and 11,505 vendors, divided into 27 sections.", photo: "https://t2.gstatic.com/images?q=tbn:ANd9GcQURzbB3H7r3_vt_sprXV-fksrdkigJHhFr_zfblLOM_xGWOeDSwWNjKKjPDaTGam8ZLf4gYbdlb47HVw", destination: bangkok)
watTraimitWithayaramWorawihan = ThingsToDo.create(name: "Wat Traimit Withayaram Worawihan", bio: "The Golden Buddha, officially titled Phra Phuttha Maha Suwanna Patimakon, commonly known in Thai as Phra Sukhothai Traimit, is a gold Maravijaya Attitude seated Buddharupa statue, with a weight of 5.5 tonnes.", photo: "https://t3.gstatic.com/images?q=tbn:ANd9GcQwYKswOLK96fuOs6oHbgKhnedelLz22r9DS-m79NuN0RBdf-sujYm4AI_R7fnGRkZ1sLns-vwiM0_Z6g", destination: bangkok)

# things to do PHUKET
krabi = ThingsToDo.create(name: "Krabi", bio: "Krabi, on southern Thailand’s west coast, is a province characterized by craggy, sheer limestone cliffs, dense mangrove forests, and more than a hundred offshore islands.", photo: "https://lp-cms-production.imgix.net/2019-06/58481926.jpg?fit=crop&q=40&sharp=10&vib=20&auto=format&ixlib=react-8.6.4", destination: phuket)
oldPhuketTown = ThingsToDo.create(name: "Old Phuket Town", bio: "Old Phuket Town, is an area of historical interest in Phuket City. The main streets of Old Phuket Town are Thalang, Phang Nga, Krabi, Dibuk, and Yoawarat. Old Phuket Town is noted for Sino-Portuguese buildings on both sides of the street.", photo: "https://t2.gstatic.com/images?q=tbn:ANd9GcTsggCZU30TB4HUSTRYO9sNfLyTRWth9dWwIPBC0q70jc-WsIzwZ7XBibfOGIGst6ksMoTqOgZu6v0HCw", destination: phuket)
khaoRang = ThingsToDo.create(name: "Khao Rang", bio: "Khao Rang is a hill in Mueang Phuket District. Located to the northwest of the city center, its summit offers views out over the town, to the south of the island", photo: "https://t0.gstatic.com/images?q=tbn:ANd9GcQZzhy6DvMBLFtkZPekovkxrCbe7rgEOhCB6oDGayDITmVb15d7lfWVcRLbS7hkG7475b4yOM4OjtbKMQ", destination: phuket)
chinprachaHouse = ThingsToDo.create(name: "Chinpracha House", bio: "Baan Chinpracha is a fine example of a Sino-colonial mansion in Phuket. Located on 98 Krabi Road in Phuket Old Town.", photo: "https://lh5.googleusercontent.com/p/AF1QipOhl-vbAzaku4nEa0K10ci3yxXru8ae4ZjxVCkY=w296-h202-n-k-no", destination: phuket)








